# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1E1E2E"

# Main text color
theme[main_fg]="#c6d0f5"

# Title color for boxes
theme[title]="#c6d0f5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bae5ff"

# Background color of selected item in processes box
theme[selected_bg]="#51576d"

# Foreground color of selected item in processes box
theme[selected_fg]="#bae5ff"

# Color of inactive/disabled text
theme[inactive_fg]="#838ba7"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#f38ba8"

# Background color of the percentage meters
theme[meter_bg]="#51576d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f38ba8"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#ee93e1" #Mauve
theme[mem_box]="#9fe5c7" #Green
theme[net_box]="#e3a1a1" #Maroon
theme[proc_box]="#89b4fa" #Blue

# Box divider line and small boxes line color
theme[div_line]="#737994"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9fe5c7"
theme[temp_mid]="#e5c890"
theme[temp_end]="#e78284"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#81c8be"
theme[cpu_mid]="#85c1dc"
theme[cpu_end]="#babbf1"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#ee93e1"
theme[free_mid]="#babbf1"
theme[free_end]="#bae5ff"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#85c1dc"
theme[cached_mid]="#bae5ff"
theme[cached_end]="#babbf1"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#ef9f76"
theme[available_mid]="#ea999c"
theme[available_end]="#e78284"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#9fe5c7"
theme[used_mid]="#81c8be"
theme[used_end]="#99d1db"

# Download graph colors (Peach -> Red)
theme[download_start]="#ef9f76"
theme[download_mid]="#ea999c"
theme[download_end]="#e78284"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#9fe5c7"
theme[upload_mid]="#81c8be"
theme[upload_end]="#99d1db"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#85c1dc"
theme[process_mid]="#babbf1"
theme[process_end]="#ee93e1"
