
$activeBorderGradient = rgba(e3a1a1ff) rgba(9fe5c7ff) rgba(e1ecb9ff) rgba(bae5ffff) rgba(ee93e1ff) rgba(94e2d5ff) rgba(bafff7ff) rgba(ACBDE3ff) rgba(ffd4baff) 45deg
$inactiveShadowColor = rgba(000000aa)
$activeShadowColor =  rgba(000000bb)

windowrule = match:class ^(brave-youtube\\.com__-Default)$, opacity 1.0 override
windowrule = match:class ^(chrome-youtube\\.com__-Default)$, opacity 1.0 override

general {
    col.active_border = $activeBorderGradient
    col.inactive_border = $inactiveBorderColor
    border_size = 3
    gaps_in = 8
    gaps_out = 12
}
group {
    col.border_active = $activeBorderGradient
}

decoration {
    # Use round window corners
    rounding = 4
    rounding_power = 3
    # active_opacity = 0.85
    # inactive_opacity = 0.78
    blur {
        enabled = true
        size = 4
        passes = 2
        noise = 0.16
    }
    shadow {
        enabled = true
        range = 20
        render_power = 6
        offset = 2 2
        ignore_window = true
        color = $activeShadowColor
        color_inactive = $inactiveShadowColor
    }
}

animations {
    bezier = easeInOutQuant, 0.76, 0, 0.24, 1
    bezier = linear, 0, 0, 1, 1

    animation = border, 1, 20, default
    animation = borderangle, 1, 55, linear, loop


  }
